language: php

php:
    - "7.1"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install --no-interaction --no-progress --no-suggest

script:
    - ./tests/run.sh -s $NTESTER_FLAGS ./tests/cases
    - ./bin/checks.sh
