language: php

php:
    - "7.4"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install --no-interaction --no-progress --no-suggest

script:
    - ./bin/checks.sh
