version: '3.3'

services:
    db:
        image: mariadb:10.3
        restart: always
        user: mysql
        volumes:
            - ${PROJECT_DIR}/.mysql:/var/lib/mysql
            - ${PROJECT_DIR}/.mysql-config:/etc/mysql/conf.d
        ports:
            - ${IP}:3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tmou
            MYSQL_USER: tmou
            MYSQL_PASSWORD: password
        networks:
            - network
    adminer:
        image: adminer
        restart: always
        ports:
            - ${IP}:8080:8080
        networks:
            - network
    webserver:
        build: .
        ports:
            - ${IP}:80:80
            - ${IP}:443:443
        volumes:
            - ${PROJECT_DIR}:/var/www/html/
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html
            MYSQL_SERVER: db
            MYSQL_PORT: 3306
            MYSQL_USER: tmou
            MYSQL_PASSWORD: password
            TRACY_DEBUG_ENABLE: 1
        depends_on:
          - db
        networks:
            network:
                aliases:
                    - tmou.test
    keycloak:
        image: keycloak/keycloak:22.0.1
        #platform: linux/amd64
        ports:
           - ${IP}:9990:8443
        volumes:
            - ${PROJECT_DIR}/.keycloak/realm-data:/opt/keycloak/data/import
            - ${PROJECT_DIR}/.keycloak/certs:/opt/keycloak/conf/certs
        entrypoint: /opt/keycloak/bin/kc.sh start --import-realm --log-level=DEBUG --hostname-strict=false --hostname-url=https://tmou.test:9990 --proxy=edge --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
        environment:
            KEYCLOAK_IMPORT: /tmp/realm-export.json
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/server.crt.pem
            KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/server.key.pem
        networks:
            - network

networks:
    network:
